<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>获取key/id</title>
    <script>
        async function handleSubmit(event) {
            event.preventDefault();
            const formData = new FormData(event.target);
            const params = new URLSearchParams();
            for (const pair of formData) {
                params.append(pair[0], pair[1]);
            }
            const url2 = 'your url'
            const response = await fetch(url2, {
                method: 'POST',
                body: params
            });

            const result = await response.json();
            document.getElementById('remix_key').textContent = result.remix_key;
            document.getElementById('remix_id').textContent = result.remix_id;
        }

        function copyToClipboard(id) {
            const text = document.getElementById(id).textContent;
            navigator.clipboard.writeText(text).then(() => {
                alert(`已复制: ${text}`);
            }, () => {
                alert('复制失败');
            });
        }
    </script>
</head>
<body>
    <h1>配置获取，获取成功后永久有效</h1>
    <form id="dataForm" onsubmit="handleSubmit(event)">
        <label for="act">第三方邮箱:</label>
        <input type="text" id="act" name="act" required><br><br>
        <label for="pwd">第三方密码:</label>
        <input type="text" id="pwd" name="pwd" required><br><br>
        <input type="submit" value="提交">
    </form>

    <div id="result"></div>
    <div>
        <p>remix_key: <span id="remix_key"></span> <button onclick="copyToClipboard('remix_key')">复制 remix_key</button></p>
        <p>remix_id: <span id="remix_id"></span> <button onclick="copyToClipboard('remix_id')">复制 remix_id</button></p>
    </div>

    <div>本网站独立运行，代码托管于<a href="">github</a></div>
</body>
</html>
